version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: smartCv-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper_data:/var/lib/zookeeper
    networks:
      - kafka_net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: smartCv-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: smartCv-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://smartCv-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka
    networks:
      - kafka_net
    depends_on:
      - zookeeper
volumes:
  zookeeper_data:
  kafka_data:

networks:
  kafka_net:
    driver: "bridge"
